# Generated by Django 5.2.14 on 2026-05-29 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.FloatField(help_text='Tasa de interés anual (%)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(30.0)])),
                ('plazo_min_anios', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('plazo_max_anios', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(40)])),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de Interés',
                'verbose_name_plural': 'Tasas de Interés',
                'ordering': ['porcentaje'],
            },
        ),
        migrations.CreateModel(
            name='PdfConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_color_primario', models.CharField(default='#1e3a5f', help_text='Color del encabezado y botón del formulario público', max_length=7, verbose_name='Color Primario del Formulario')),
                ('form_color_secundario', models.CharField(default='#4a90d9', help_text='Color de acentos y hover del formulario público', max_length=7, verbose_name='Color Secundario del Formulario')),
                ('form_color_califica', models.CharField(default='#16a34a', max_length=7, verbose_name="Color 'Califica'")),
                ('form_color_no_califica', models.CharField(default='#dc2626', max_length=7, verbose_name="Color 'No Califica'")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pdf/', verbose_name='Logo')),
                ('color_primario', models.CharField(default='#1e3a5f', max_length=7, verbose_name='Color Primario del PDF')),
                ('color_secundario', models.CharField(default='#4a90d9', max_length=7, verbose_name='Color Secundario del PDF')),
                ('header_text', models.CharField(default='Simulación de Crédito Hipotecario', max_length=200, verbose_name='Texto del Encabezado')),
                ('footer_text', models.TextField(default='Este documento es una simulación y no constituye una oferta de crédito.', verbose_name='Texto del Pie de Página')),
                ('valor_uf', models.FloatField(default=38000.0, help_text='Valor de la UF en pesos chilenos. Actualizar periódicamente.', verbose_name='Valor UF actual ($)')),
                ('mostrar_deudas', models.BooleanField(default=True, verbose_name='Mostrar Deudas en PDF')),
                ('mostrar_tabla_amortizacion', models.BooleanField(default=False, verbose_name='Mostrar Tabla de Amortización')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración PDF',
                'verbose_name_plural': 'Configuración PDF',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('valor_propiedad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Propiedad (UF)')),
                ('pie', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pie (UF)')),
                ('monto_credito', models.FloatField(verbose_name='Monto Crédito (UF)')),
                ('plazo_anios', models.IntegerField(verbose_name='Plazo (años)')),
                ('tasa_interes', models.FloatField(verbose_name='Tasa Interés (%)')),
                ('tasa_interes_nombre', models.CharField(max_length=100, verbose_name='Nombre Tasa')),
                ('renta_bruta_clp', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Renta Bruta Mensual (CLP)')),
                ('deudas_vigentes_clp', models.FloatField(default=0, verbose_name='Deudas Vigentes Mensuales (CLP)')),
                ('valor_uf', models.FloatField(verbose_name='Valor UF al momento de evaluación')),
                ('cuota_mensual', models.FloatField(verbose_name='Cuota Mensual (UF)')),
                ('cuota_mensual_clp', models.FloatField(verbose_name='Cuota Mensual (CLP)')),
                ('relacion_cuota_ingreso', models.FloatField(verbose_name='Relación Cuota/Ingreso (%)')),
                ('renta_minima_requerida_clp', models.FloatField(verbose_name='Renta Mínima Requerida (CLP)')),
                ('costo_total_credito', models.FloatField(verbose_name='Costo Total del Crédito (UF)')),
                ('califica', models.BooleanField(verbose_name='¿Califica?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
