# Generated by Django 5.2.14 on 2026-06-16 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=200, verbose_name='Edificio / Proyecto')),
                ('comuna', models.CharField(max_length=120, verbose_name='Comuna')),
                ('entrega', models.CharField(default='Entrega Inmediata', max_length=120, verbose_name='Entrega')),
                ('tipologia', models.CharField(help_text='Ej: 2D + 1B', max_length=60, verbose_name='Tipología')),
                ('precio_uf', models.FloatField(help_text='Precio de la unidad en UF. Se usa para filtrar contra el presupuesto del cliente.', validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio (UF)')),
                ('superficie_total_m2', models.FloatField(default=0, verbose_name='Superficie Total (m²)')),
                ('superficie_util_m2', models.FloatField(default=0, verbose_name='Superficie Útil (m²)')),
                ('superficie_terraza_m2', models.FloatField(default=0, verbose_name='Superficie Terraza (m²)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen')),
                ('enlace', models.URLField(blank=True, default='', help_text='A dónde lleva el botón de la tarjeta (ej: https://wa.me/569...).', max_length=500, verbose_name='Enlace (WhatsApp / embudo)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('orden', models.IntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['orden', 'precio_uf'],
            },
        ),
        migrations.AlterModelOptions(
            name='pdfconfig',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuración'},
        ),
        migrations.RemoveField(
            model_name='pdfconfig',
            name='color_primario',
        ),
        migrations.RemoveField(
            model_name='pdfconfig',
            name='color_secundario',
        ),
        migrations.RemoveField(
            model_name='pdfconfig',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='pdfconfig',
            name='header_text',
        ),
        migrations.RemoveField(
            model_name='pdfconfig',
            name='mostrar_deudas',
        ),
        migrations.RemoveField(
            model_name='pdfconfig',
            name='mostrar_tabla_amortizacion',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='califica',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='costo_total_credito',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cuota_mensual',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cuota_mensual_clp',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='deudas_vigentes_clp',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='monto_credito',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='pie',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='relacion_cuota_ingreso',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='renta_bruta_clp',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='renta_minima_requerida_clp',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='valor_propiedad',
        ),
        migrations.AddField(
            model_name='pdfconfig',
            name='factor_endeudamiento',
            field=models.FloatField(default=3.6, help_text='El dividendo máximo = sueldo líquido / este factor. Por defecto 3,6 (≈27,8% del sueldo).', validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Factor de Endeudamiento'),
        ),
        migrations.AddField(
            model_name='pdfconfig',
            name='form_color_fondo',
            field=models.CharField(default='#FDEFD6', help_text='Fondo crema de las tarjetas/secciones.', max_length=7, verbose_name='Color de Fondo'),
        ),
        migrations.AddField(
            model_name='pdfconfig',
            name='pie_pct_default',
            field=models.FloatField(default=10.0, help_text='Porcentaje de pie preseleccionado en la calculadora.', verbose_name='Pie por defecto (%)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='complementa_renta',
            field=models.BooleanField(default=False, verbose_name='¿Complementa renta?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='dividendo_clp',
            field=models.FloatField(default=0, verbose_name='Dividendo Mensual (CLP)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='dividendo_uf',
            field=models.FloatField(default=0, verbose_name='Dividendo Mensual (UF)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='factor_endeudamiento',
            field=models.FloatField(default=3.6, verbose_name='Factor de Endeudamiento'),
        ),
        migrations.AddField(
            model_name='submission',
            name='financiamiento_clp',
            field=models.FloatField(default=0, verbose_name='Financiamiento Banco (CLP)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='financiamiento_uf',
            field=models.FloatField(default=0, verbose_name='Financiamiento Banco (UF)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pie_clp',
            field=models.FloatField(default=0, verbose_name='Pie / Ahorro (CLP)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pie_pct',
            field=models.FloatField(default=0, verbose_name='Pie (%)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pie_uf',
            field=models.FloatField(default=0, verbose_name='Pie / Ahorro (UF)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='precio_maximo_clp',
            field=models.FloatField(default=0, verbose_name='Precio Máximo Depto (CLP)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='precio_maximo_uf',
            field=models.FloatField(default=0, verbose_name='Precio Máximo Depto (UF)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='sueldo_2_clp',
            field=models.FloatField(default=0, verbose_name='Sueldo Nº2 (CLP)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='sueldo_liquido_clp',
            field=models.FloatField(default=0, verbose_name='Sueldo Líquido (CLP)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='unidades_encontradas',
            field=models.IntegerField(default=0, verbose_name='Unidades Encontradas'),
        ),
        migrations.AlterField(
            model_name='pdfconfig',
            name='form_color_primario',
            field=models.CharField(default='#5D1314', help_text='Color de títulos, botones y encabezados de tabla.', max_length=7, verbose_name='Color Primario'),
        ),
        migrations.AlterField(
            model_name='pdfconfig',
            name='form_color_secundario',
            field=models.CharField(default='#A2998F', help_text='Color de acentos, bordes y textos de apoyo.', max_length=7, verbose_name='Color Secundario'),
        ),
        migrations.AlterField(
            model_name='pdfconfig',
            name='valor_uf',
            field=models.FloatField(default=38000.0, help_text='Valor de la UF en pesos chilenos. Actualizar periódicamente (fuente: SII.cl).', verbose_name='Valor UF actual ($)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='plazo_anios',
            field=models.IntegerField(default=0, verbose_name='Plazo (años)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tasa_interes',
            field=models.FloatField(default=0, verbose_name='Tasa Interés (%)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tasa_interes_nombre',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre Tasa'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='valor_uf',
            field=models.FloatField(default=0, verbose_name='Valor UF al momento de evaluación'),
        ),
    ]
