# Generated by Django 5.2.14 on 2026-07-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_peterman_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificado', 'Calificado'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', help_text='Etapa del lead en el pipeline comercial.', max_length=20, verbose_name='Estado'),
        ),
    ]
