"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if python-dotenv is available (development)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

# DEBUG: por defecto False (falla segura). Si en producción el .env no carga,
# la app no queda en modo debug exponiendo detalles internos. En desarrollo
# local el .env debe definir DJANGO_DEBUG=True.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# SECRET_KEY: obligatoria en producción; el fallback sólo aplica con DEBUG.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-clave-solo-para-desarrollo-local'
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY no está definida. Genera una con '
            '"python -c \"from django.core.management.utils import get_random_secret_key; '
            'print(get_random_secret_key())\"" y configúrala como variable de entorno. '
            'En desarrollo local basta con DJANGO_DEBUG=True en el archivo .env.'
        )

_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'calculadora',
]

# Protección contra fuerza bruta en el login (django-axes):
# tras AXES_FAILURE_LIMIT intentos fallidos por combinación usuario+IP,
# bloquea por AXES_COOLOFF_TIME horas. Se resetea con un login exitoso.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # horas
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_RESET_ON_SUCCESS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'calculadora' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database — usa DATABASE_URL si está definida (PostgreSQL), SQLite en su defecto
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Formato numérico chileno: separador de miles "." y decimal ","
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = 'media/'
# En cPanel las imágenes viven en la carpeta media/ del proyecto (persistente).
# DJANGO_MEDIA_ROOT permite apuntar a otra ruta si hace falta.
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Caché en archivos: el contador anti-spam del formulario debe compartirse
# entre los procesos de Passenger y sobrevivir a sus reinicios (la caché en
# memoria por defecto se pierde y no se comparte).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.environ.get('DJANGO_CACHE_DIR', str(BASE_DIR / 'tmp' / 'django_cache')),
    }
}

# Ruta del admin. Configurable para no exponerla en la ruta obvia /admin/.
ADMIN_URL = os.environ.get('DJANGO_ADMIN_URL', 'admin/').strip('/') + '/'

# La sesión del admin expira tras 8 horas (por defecto Django usa 2 semanas).
SESSION_COOKIE_AGE = 60 * 60 * 8

# ─── Security settings for production ─────────────────────────────────────────
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # La calculadora se incrusta como iframe en el sitio principal. Para que la
    # cookie CSRF viaje aunque el sitio embebedor esté en otro dominio (ej. el
    # preproductivo syscode.cloud), su SameSite debe ser 'None' (exige Secure,
    # ya activo arriba). Configurable: cuando el sitio viva en
    # petermanncapitalgroup.cl el embed es same-site y puede volver a 'Lax'.
    CSRF_COOKIE_SAMESITE = os.environ.get('DJANGO_CSRF_COOKIE_SAMESITE', 'None')
    # El formulario público no usa sesión: sólo el admin, que nunca se
    # embebe. Lax evita que la sesión del admin viaje en peticiones cross-site.
    SESSION_COOKIE_SAMESITE = 'Lax'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # El admin nunca debe embeberse; la calculadora pública se exceptúa con
    # @xframe_options_exempt + CSP frame-ancestors en su vista.
    X_FRAME_OPTIONS = 'DENY'

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SESSION_COOKIE_HTTPONLY = True

# Dominios autorizados a incrustar la calculadora en un <iframe>.
# La vista pública envía CSP frame-ancestors con esta lista (en vez de
# permitir cualquier sitio). Separar por comas en la variable de entorno.
_frame_ancestors = os.environ.get(
    'DJANGO_FRAME_ANCESTORS',
    'https://petermanncapitalgroup.cl,https://www.petermanncapitalgroup.cl,'
    'https://petermanncapitalgroup.syscode.cloud,'
    'https://calculadora.petermanncapitalgroup.cl'
)
CALC_FRAME_ANCESTORS = [h.strip() for h in _frame_ancestors.split(',') if h.strip()]

# CSRF trusted origins (set your domain in production)
_csrf = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [h.strip() for h in _csrf.split(',') if h.strip()]

# ─── Logging ──────────────────────────────────────────────────────────────────
# En producción los errores (500, intentos sospechosos de host/CSRF, bloqueos
# de axes) se escriben en un archivo rotativo para poder revisarlos.
if not DEBUG:
    LOG_FILE = Path(os.environ.get('DJANGO_LOG_FILE', BASE_DIR / 'logs' / 'django.log'))
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'simple': {'format': '{asctime} {levelname} {name}: {message}', 'style': '{'},
        },
        'handlers': {
            'file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': str(LOG_FILE),
                'maxBytes': 5 * 1024 * 1024,
                'backupCount': 5,
                'formatter': 'simple',
                'encoding': 'utf-8',
            },
        },
        'loggers': {
            'django': {'handlers': ['file'], 'level': 'WARNING'},
            'django.security': {'handlers': ['file'], 'level': 'WARNING', 'propagate': False},
            'axes': {'handlers': ['file'], 'level': 'WARNING', 'propagate': False},
        },
    }
